In [20]:
import numpy as np

Premier exemple de décomposition $LU$.

In [21]:
# illustration de la methode LU
# nettoyage de la premiere colonne
A=np.array([[1, 2, -1],[ 2, 1, 1],[ -1, 0, 1]])
M1=np.array([[ 1, 0, 0], [-A[1][0]/A[0][0], 1, 0],[-A[2][0]/A[0][0] , 0, 1]])
U1= M1@A
print('U1=\n',U1)
#nettoyage de la deuxieme colonne
M2=np.array([[1, 0 ,0],[0, 1, 0],[0 ,-U1[2][1]/U1[1][1], 1]])
U2= M2@U1
#inverses des manipulations de lignes
L1=np.linalg.inv(M1)
L2=np.linalg.inv(M2)
# factorisation LU
U=U2
L=L1@L2
print('Decomposition LU pour A :\n','L=\n',L,'\n U=\n',U)



U1=
 [[ 1.  2. -1.]
 [ 0. -3.  3.]
 [ 0.  2.  0.]]
Decomposition LU pour A :
 L=
 [[ 1.          0.          0.        ]
 [ 2.          1.          0.        ]
 [-1.         -0.66666667  1.        ]] 
 U=
 [[ 1.  2. -1.]
 [ 0. -3.  3.]
 [ 0.  0.  2.]]


Exercice 1

In [ ]:
# illustration de la methode LU
# nettoyage de la premiere colonne
A=np.array([[3, 2, 0, 0],[1, 4, 1, 3],[2, 0, 3, 0],[1, 2, 1, 0]])
M1=np.array([[ 1, 0, 0], [-A[1][0]/A[0][0], 1, 0],[-A[2][0]/A[0][0] , 0, 1]])
U1= M1@A
print('U1=\n',U1)
#nettoyage de la deuxieme colonne
M2=np.array([[1, 0 ,0],[0, 1, 0],[0 ,-U1[2][1]/U1[1][1], 1]])
U2= M2@U1
#inverses des manipulations de lignes
L1=np.linalg.inv(M1)
L2=np.linalg.inv(M2)
# factorisation LU
U=U2
L=L1@L2
print('Decomposition LU pour A :\n','L=\n',L,'\n U=\n',U)

Exercice 2

Quand le pivot devient trop petit.

In [22]:
a=1e-17
A=np.array([[a, 1],[1, 1]])
b= np.array([1,2])
M1=np.array([[1, 0],[-a**(-1), 1]])
U1= M1@A
# U1x=b1
b1=M1@b
#solution après factorisation
x1=np.linalg.solve(U1,b1)
#solution directe
x=np.linalg.solve(A,b)
print(x1,x)

[0. 1.] [1. 1.]


Exercice 3

### Avec scipy

In [23]:
import scipy
scipy.linalg.lu(A)

ModuleNotFoundError: No module named 'scipy'