## TP4

### Exercice 1:

In [1]:
import numpy as np
import matplotlib.pyplot as plt

A = np.array([[1,1,3],[0,2,4],[0,0,4]])
b = np.array([1,2,4])
taille = 3

def remontee(A,b):
    x3 = b[2]/A[2][2]
    x2 = (b[1]-A[1][2]*x3)/A[1][1]
    x1 = (b[0]-(A[0][1]*x2+A[0][2]*x3))/A[0][0]
    return x1,x2,x3

print(remontee(A,b))

(-1.0, -1.0, 1.0)


### Exercice 2:

###### 1-

In [2]:
def matTriangSup(taille):
    A = np.triu(np.random.rand(taille,taille))
    return A

print(matTriangSup(taille))

[[0.18731084 0.77760227 0.95675751]
 [0.         0.2111375  0.09806114]
 [0.         0.         0.51135284]]


###### 2- 3-

In [3]:
def inversible(A):
    return (np.abs(np.linalg.det(A)) != 0)

print(inversible(A))

def remonteeGen(A,b,taille):
    if inversible(A):
        x = np.zeros((taille))
        for i in range(taille-1, -1, -1):
            x[i] = b[i]
            for j in range(len(A)):
                x[i] -= A[i][j]*x[j] if j != i else 0
            x[i] /= A[i][i]
        return x
    else :
        raise np.linalg.LinAlgError("pas inversible")

x = remonteeGen(A,b,taille)
print(x)

True
[-1. -1.  1.]


###### 4-

In [4]:
def normeResidu(A,x,b):
    return max(np.abs(A@x - b))


print(normeResidu(A,x,b))

0.0


#### Exercice 3

In [2]:
for i in range(2,1001):
    d = np.random.rand(i)
    C = matTriangSup(i)
    x = remonteeGen(C,d,i)

y = range(2,1001)

plt.plot(y,x)
plt.show()

NameError: name 'np' is not defined