In [42]:
import numpy as np
import scipy as sp

Définition de la fonction Choleski

In [43]:
def Choleski_i1(A, H, i):
    return (1 / H[1, 1]) * A[i, 1]

def Choleski_ij(A, H, i, j):
    return (1/ H[j,j]) * (A[i,j] - 
                        (sum( H[i,k] * H[j,k]
                             for k in range(1, j-1)))
                       )

                        
def Choleski_ii(A, H, i):
    return np.sqrt(
        A[i,i] - (sum( (H[i,k])**2
                             for k in range(1, i-1)))
    )

def Choleski(A):
    if not isinstance(A,np.ndarray): #est-ce que A est une matrice
        return "l'argument doit être une matrice"
    
    if A.shape[0]!=A.shape[1]: #est-ce que A est carrée
        return "l'argument doit être une matrice carrée"
    if (A-A.T).any()!=np.zeros(A.shape).any(): #est-ce que A est symmétrique
        return "l'argument doit être une matrice symétrique"
    L=np.zeros(A.shape)
    
    
    for e in range(A.shape[0]):
        if A[e,e] < 0:
            return "L'argument n'est pas une matrice définie positive"
    
    H = sp.linalg.hilbert(A.shape[0])
    L[0,0]=np.sqrt(A[0,0])
    for i in range (A.shape[0]):
        for j in range (i):
            if j == 1:
                L[i,j] = Choleski_i1(A, H, i)
            else:
                L[i,j] = Choleski_ij(A, H, i, j)
        L[i,i] = Choleski_ii(A, H, i)
    return L


On définit la matrice de Hilbert de taille 5 puis on lui applique la fonction Choleski.

In [44]:
from scipy.linalg import hilbert

In [45]:
A = hilbert(5)
C = Choleski(A)

In [46]:
print(C@np.transpose(C))
print(A)

[[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.58333333 0.59967937 0.47141016 0.38867513]
 [0.33333333 0.59967937 0.87361111 0.90601133 0.76110495]
 [0.25       0.47141016 0.90601133 1.21980159 1.15102925]
 [0.2        0.38867513 0.76110495 1.15102925 1.27486536]]
[[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]]


In [47]:
A = np.array([[1,2,3,4],[2,5,6,7],[3,6,-1,8],[4,7,8,-3]])
A

array([[ 1,  2,  3,  4],
       [ 2,  5,  6,  7],
       [ 3,  6, -1,  8],
       [ 4,  7,  8, -3]])

In [48]:
Choleski(A)

"L'argument n'est pas une matrice définie positive"

La matrice $A$ est bien symétrique, mais elle n'est pas définie positive car il y a -1 et -3 sur la diagonale

Recopier les fonctions Remontee et Descente du TP précédent.

In [49]:
def Remontee(A,b):
    dim=np.shape(b)[0]
    if dim!=np.shape(A)[0]:
        print("Problème de dimension entre A et b")
    x=np.zeros(dim)
    for i in range(n):
        if A[n-1-i,n-1-i]<10**(-12):
            print('Attention, la matrice est presque singulière pour le rang', i)
        s=x[n-i:]@A[n-i-1,n-i:]
        x[n-1-i]=(1/A[n-1-i,n-1-i])*(b[n-1-i]-s)
    return x


def Descente(A,b):
    dim=np.shape(b)[0]
    if dim!=np.shape(A)[0]:
        print("Problème de dimension entre A et b")
    x=np.zeros(dim)
    for i in range(n):
        if A[i,i]<10**(-12):
            print('Attention, la matrice est presque singulière pour le rang', i)
        s=x[0:i:]@A[i,0:i]
        x[i]=(1/A[i,i])*(b[i]-s)
    return x

On les utilise pour résoudre le système proposé. 

In [50]:
B = np.ones(5)



Définition de la fonction Thomas quand la matrice est tridiagonale. 

In [51]:
def LU_Thomas(A):


SyntaxError: incomplete input (310997826.py, line 1)

La matrice $A$ est créée avec la fonction np.eye.